package com.virtuslab.shared_indexes.config

/**
 *
 * @param indexServerUrl The url where server will be running.
 *                       It will be a prefix for download URLs
 *                       in index files generated by cdn layout tool.
 *                       Make sure it matches the location
 *                       where indexes will actually be served.
 */
case class IndexStorageConfig(
    indexServerUrl: Option[String]
)
